CREATE DATABASE BLINKIT
USE BLINKIT

SELECT TOP 5* FROM ORDERS
SELECT TOP 3* FROM ORDERDETAILS
SELECT TOP 5* FROM PRODUCTS

SELECT * FROM ORDERS O INNER JOIN ORDERDETAILS OD
ON O.ORDER_ID = OD.ORDER_ID INNER JOIN PRODUCTS PD 
ON OD.PRODUCT_ID = PD.PRODUCT_ID


SELECT * FROM ORDERS O LEFT JOIN ORDERDETAILS OD
ON O.ORDER_ID = OD.ORDER_ID LEFT JOIN PRODUCTS PD 
ON OD.PRODUCT_ID = PD.PRODUCT_ID



----Total Revenue-----

CREATE VIEW TOTAL_REVENUE
AS
SELECT CAST(SUM(REVENUE) AS DECIMAL(10,2)) AS TOTAL_REVENUE FROM
ORDERDETAILS


SELECT * FROM TOTAL_REVENUE

----TOTAL ORDERS-----

CREATE VIEW TOTAL_ORDERS
AS
SELECT COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDERS
FROM ORDERS

SELECT * FROM TOTAL_ORDERS


-----TOTAL CUSTOMERS------

CREATE VIEW TOTAL_CUSTOMERS
AS 
SELECT COUNT(DISTINCT(CUSTOMER_ID))AS TOTAL_CUSTOMERS
FROM CUSTOMERS

SELECT * FROM  TOTAL_CUSTOMERS

---TOP SELLING PRODUCTS----

CREATE VIEW TOP_SELLING_PRODUCTS
AS
SELECT TOP 10
PD.PRODUCT_NAME,
SUM(OD.QUANTITY)AS UNITS_SOLD,
CAST(SUM(OD.REVENUE)AS DECIMAL(10,2))AS TOTAL_REVENUE 
FROM PRODUCTS PD INNER JOIN ORDERDETAILS OD 
ON PD.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY PD.PRODUCT_NAME
ORDER BY UNITS_SOLD DESC

SELECT * FROM TOP_SELLING_PRODUCTS


---Revenue By Category---

SELECT PD.CATEGORY,CAST(SUM(OD.REVENUE)AS DECIMAL(10,2)) AS TOTAL_REVENUE
FROM PRODUCTS PD INNER JOIN ORDERDETAILS OD 
ON PD.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY PD.CATEGORY
ORDER BY TOTAL_REVENUE DESC


-- SALES SUMMARY---

CREATE VIEW SALES_SUMMARY
AS 
SELECT 
	COUNT(DISTINCT(O.ORDER_ID))AS TOTAL_ORDERS,
	CAST(SUM(OD.REVENUE) AS DECIMAL(10,2))AS TOTAL_REVENUE,
	CAST(AVG(O.ORDER_TOTAL)AS DECIMAL(10,2)) AS AVERAGE_OREDER_VALUE
FROM ORDERS O INNER JOIN ORDERDETAILS OD 
ON O.ORDER_ID = OD.ORDER_ID

SELECT * FROM SALES_SUMMARY


---Payment Method Analysis
CREATE VIEW PAYMENT_METHOD_VIEW
AS
SELECT 
PAYMENT_METHOD,
COUNT(*) AS TOTAL_ORDERS,
CAST(SUM(ORDER_TOTAL)AS DECIMAL(10,2)) AS TOTAL_AMOUNT
FROM ORDERS
GROUP BY PAYMENT_METHOD




--Delivery Performance
SELECT DELIVERY_STATUS,COUNT(*) AS TOTAL_ORDERS
FROM DELIVERY_PERFORMANCE
GROUP BY DELIVERY_STATUS




---Customer Segmentation
CREATE VIEW CUSTOMER_SEGMENTATION
AS
SELECT 
	CUSTOMER_SEGMENT,
	COUNT(DISTINCT(CUSTOMER_ID))AS TOTAL_CUSTOMERS
FROM CUSTOMERS
GROUP BY CUSTOMER_SEGMENT


---Inventory Damage Analysis

CREATE VIEW INVENTORY_DETAIL_VIEW
AS
SELECT 
PD.CATEGORY,
	SUM(I.STOCK_RECEIVED) AS STOCK_RECEIVED,
	SUM(I.DAMAGED_STOCK)AS STOCK_DAMAGED,
	CAST(100*SUM(I.DAMAGED_STOCK)/SUM(I.STOCK_RECEIVED)AS DECIMAL(10,1)) AS DAMAGE_PERCENTAGE
FROM PRODUCTS PD
INNER JOIN INVENTORY I 
ON PD.PRODUCT_ID = I.PRODUCT_ID
GROUP BY PD.CATEGORY



---Delivery KPI View
CREATE VIEW DELIVERY_KPI_VIEW
AS
SELECT DELIVERY_STATUS,
COUNT(ORDER_ID) AS TOTAL_ORDERS,
AVG(DELIVERY_TIME_MINUTES) AS AVG_DELIVERY_VARIANCE
FROM DELIVERY_PERFORMANCE
GROUP BY DELIVERY_STATUS



SELECT * FROM DELIVERY_PERFORMANCE


--Product Performance View
CREATE VIEW PRODUCT_PERFORMANCE
AS
SELECT PD.PRODUCT_NAME,SUM(OD.QUANTITY) AS UNITS_SOLD,
CAST(SUM(OD.REVENUE)AS DECIMAL(10,2))AS TOTAL_AMOUNT
FROM PRODUCTS PD INNER JOIN ORDERDETAILS OD
ON PD.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY PRODUCT_NAME

SELECT * FROM PRODUCT_PERFORMANCE
ORDER BY UNITS_SOLD DESC
